create table `wx_users` (
	`id` int unsigned not null auto_increment,
    `openid` varchar(255),
    `subscribe` int,
	`name` varchar(64),
	`nickname` varchar(64),
    `sex` int,
    `language` varchar(64),
    `city` varchar(64),
    `province` varchar(64),
    `country` varchar(64),
    `headimgurl` varchar(512),
    `subscribe_time` int,
    `unionid` varchar(512),
    `groupid` int,
    `tagid_list` varchar(215),
	`email` varchar(64),
	`password` varchar(255),
	`mobile`	varchar(64),
	`remember_token` varchar(255),
    `remark` varchar(255),
	`deleted_at` datetime default null,
	`created_at` timestamp default current_timestamp,
	`updated_at` timestamp not null default current_timestamp  on update current_timestamp,
	primary key (`id`),
	unique key (`email`),
    unique key (`openid`),
	unique key (`mobile`)
) engine=InnoDB default charset=utf8 collate=utf8_unicode_ci;